// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/e154/smart-home/api/server_v1/stub/models"
)

// NewAddNodeParams creates a new AddNodeParams object
// with the default values initialized.
func NewAddNodeParams() AddNodeParams {
	var ()
	return AddNodeParams{}
}

// AddNodeParams contains all the bound params for the add node operation
// typically these are obtained from a http.Request
//
// swagger:parameters addNode
type AddNodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*request params
	  In: body
	*/
	PostNodeParams *models.NodeModel
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddNodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.NodeModel
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("postNodeParams", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.PostNodeParams = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
