// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetNodeByIDHandlerFunc turns a function with the right signature into a get node by Id handler
type GetNodeByIDHandlerFunc func(GetNodeByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNodeByIDHandlerFunc) Handle(params GetNodeByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetNodeByIDHandler interface for that can handle valid get node by Id params
type GetNodeByIDHandler interface {
	Handle(GetNodeByIDParams, interface{}) middleware.Responder
}

// NewGetNodeByID creates a new http.Handler for the get node by Id operation
func NewGetNodeByID(ctx *middleware.Context, handler GetNodeByIDHandler) *GetNodeByID {
	return &GetNodeByID{Context: ctx, Handler: handler}
}

/*GetNodeByID swagger:route GET /node/{id} node getNodeById

get node by id

*/
type GetNodeByID struct {
	Context *middleware.Context
	Handler GetNodeByIDHandler
}

func (o *GetNodeByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNodeByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
