// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/e154/smart-home/api/server_v1/stub/models"
)

// GetNodeByIDOKCode is the HTTP code returned for type GetNodeByIDOK
const GetNodeByIDOKCode int = 200

/*GetNodeByIDOK success

swagger:response getNodeByIdOK
*/
type GetNodeByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetNodeByIDOKBody `json:"body,omitempty"`
}

// NewGetNodeByIDOK creates GetNodeByIDOK with default headers values
func NewGetNodeByIDOK() *GetNodeByIDOK {
	return &GetNodeByIDOK{}
}

// WithPayload adds the payload to the get node by Id o k response
func (o *GetNodeByIDOK) WithPayload(payload *models.GetNodeByIDOKBody) *GetNodeByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get node by Id o k response
func (o *GetNodeByIDOK) SetPayload(payload *models.GetNodeByIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodeByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetNodeByIDDefault error

swagger:response getNodeByIdDefault
*/
type GetNodeByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetNodeByIDDefault creates GetNodeByIDDefault with default headers values
func NewGetNodeByIDDefault(code int) *GetNodeByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetNodeByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get node by Id default response
func (o *GetNodeByIDDefault) WithStatusCode(code int) *GetNodeByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get node by Id default response
func (o *GetNodeByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get node by Id default response
func (o *GetNodeByIDDefault) WithPayload(payload *models.ErrorModel) *GetNodeByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get node by Id default response
func (o *GetNodeByIDDefault) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodeByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
