root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = """
  CGO_ENABLED=1 \
  CGO_CFLAGS=-I$HOME/.vosk/libvosk \
  CGO_LDFLAGS=-L$HOME/.vosk/libvosk \
  LD_LIBRARY_PATH=$HOME/.vosk/libvosk:$LD_LIBRARY_PATH \
  DYLD_LIBRARY_PATH=$HOME/.vosk/libvosk \
  go build \
  -o ./server-darwin-10.6-arm64 ./main.go
  """
  delay = 1000
  exclude_dir = ["data", "conf", "static_source", "test", "tmp", "webdav"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = """
  DYLD_LIBRARY_PATH=$HOME/.vosk/libvosk \
  ./server-darwin-10.6-arm64
  """
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 2000
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
