run:
  deadline: 3m
  tests: true
  skip-dirs:
    - tmp
    - tmp/stream
linters:
  enable:
    - gofmt
    - goimports
    - gosimple
    - ineffassign
  #  - deadcode
  #  - varcheck
  #  - errcheck
  #  - staticcheck
  #  - structcheck
  #  - unused
  #  - govet
  disable-all: true
go: '1.20'
