run:
  deadline: 3m
  tests: true
  skip-dirs:
    - tmp
    - tmp/stream
linters:
  enable:
    - deadcode
    - gofmt
    - goimports
    - varcheck
    - errcheck
    - gosimple
    - ineffassign
  #   - staticcheck
  #   - structcheck
  #   - unused
  #   - govet
  disable-all: true
go: '1.18'
