// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ErrorModelErrorsItems error model errors items
// swagger:model errorModelErrorsItems
type ErrorModelErrorsItems struct {

	// тип ишибки
	Code string `json:"code,omitempty"`

	// поле вызвавшее ошибку
	Field string `json:"field,omitempty"`

	// описание
	Message string `json:"message,omitempty"`
}

// Validate validates this error model errors items
func (m *ErrorModelErrorsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorModelErrorsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorModelErrorsItems) UnmarshalBinary(b []byte) error {
	var res ErrorModelErrorsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
