// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NodeModel node model
// swagger:model NodeModel
type NodeModel struct {

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// update at
	UpdateAt strfmt.DateTime `json:"update_at,omitempty"`
}

// Validate validates this node model
func (m *NodeModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var nodeModelTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["enabled","disabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		nodeModelTypeStatusPropEnum = append(nodeModelTypeStatusPropEnum, v)
	}
}

const (
	// NodeModelStatusEnabled captures enum value "enabled"
	NodeModelStatusEnabled string = "enabled"
	// NodeModelStatusDisabled captures enum value "disabled"
	NodeModelStatusDisabled string = "disabled"
)

// prop value enum
func (m *NodeModel) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, nodeModelTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *NodeModel) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NodeModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeModel) UnmarshalBinary(b []byte) error {
	var res NodeModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
