// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Server API
Server API

Terms Of Service:

https://e154.ru/


    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 0.0.1
    Contact: <filippov.a@e154.ru>

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/html

swagger:meta
*/
package restapi
