baseurl: "https://e154.github.io/"
languageCode: "ru-ru"
title: "Smart home"
theme: "default"
contentDir: "content/ru"
publishDir: "public/ru"
googleAnalytics: ""

params:
  locale: "ru-RU"
  name: "Your name"
  description: "Your description"
  favicon: "favicon.ico"

  main_menu:
    brand: "Умный дом"

    links:
      - title: "Домой"
        url : "/"
      - title : "С чего начать"
        url : "/getting-started"
      - title : "api"
        url : "/api_v1"

  hero:
    slogan    : "Система для создания современного умного дома"
    subtitle  : "Подойдёт как для любителей - электронщиков, так и профессионалам своего дела"
    buttonText: "Подробнее"

  feature:
    headline   : "Это то, что Вы искали!"
    description: "Smart Home - Система с открытым исходным кодом, которую можно скачать бесплатно, без регистраций, и смс. Безвоздмездно! Большое количество функционала уже присутствует из коробки, и хорошо подаётся расширению. Smart Home система позволяет получить результат в кратчайшие сроки."
    buttonText : "С чего начать"

  services:
    headline: "Сервисы"

    row1:
      - icon: "fa-users"
        title: "Система доступа основанная на ролях"
        description: "Позволяет гибко управлять доступом к оборудованию, и системным компонентам."
      - icon: "fa-cogs"
        title: "Панель управления"
        description: "Удобная панель управления, и конфигурирования оборудования."
      - icon: "fa-paper-plane"
        title: "Готов к использования"
        description: "Вы можете использовать Smart home как есть, или Вы можете изменять его под свои нужды!"
      - icon: "fa-line-chart"
        title: "Расширяемость"
        description: "Система расширяема настолько, насколько это требут поставленная задача"

    row2:
      - icon: "fa-paper-plane-o"
        title: "Информирование"
        description: "Гибкая система информирование будет держать Вас в курсе всех событий"
      - icon: "fa-server"
        title: "Микросервисная архитектура"
        description: "Система разбита на микросервисы для улучшения производительности и расширяемости"
      - icon: "fa-file-text-o"
        title: "Javascript скрипты"
        description: "Система скриптов позволяет писать сценарии прямо в окне браузера"
      - icon: "fa-heart"
        title: "Сделано с любовью"
        description: "Весь код системы Умного дома написан с любовью и вниманием к квждой мелочи"

  source:
    headline: "Скачайте исходный код проекта!"
    server:
      text: "Сервер"
      link: "//github.com/e154/smart-home"
    configurator:
      text: "Конфигуратор"
      link: "//github.com/e154/smart-home-configurator"
    node:
      text: "Нода"
      link: "//github.com/e154/smart-home-node"

  download:
    button: "Скачать"
    server:
      text: "Сервер"
      description: "Ядро системы Умной дом, сервер управляющий логикой и бизнес-процессами системы, является сердцем умного дома."
      link: "//github.com/e154/smart-home"
    configurator:
      text: "Конфигуратор"
      description: "Клиентское приложение для конфигурирования систем умного дома, под поставленные задачи."
      link: "//github.com/e154/smart-home-configurator"
    node:
      text: "Нода"
      description: "Компонент системы отвечающий за связь сервера с активными устройствами, часть системы умный дом."
      link: "//github.com/e154/smart-home-node"

  footer:
    licensed: "Code licensed <a href='https://github.com/e154/smart-home/blob/master/LICENSE'>MIT</a>, docs <a href='http://creativecommons.org/licenses/by/3.0/'>CC BY 3.0</a>."

  getting-started:
    links:
      - title: "Обзор"
        url: "#overview"
      - title: "Системные требования"
        url: "#requirements"
      - title: "Загрузка"
        url: "#download"
      - title: "Что входит в пакеты"
        url: "whats-included"
        pages:
          - title: "Сервер"
            url: "#server"
          - title: "Конфигуратор"
            url: "#configurator"
          - title: "Нода"
            url: "Нода"
      - title: "Установка"
        url: "#install"
        pages:
          - title: Install mkdir
            url: ""
          - title: Install download and unpack
            url: ""
          - title: Install server conf
            url: ""
          - title: Install configuration conf
            url: ""
          - title: Install node conf
            url: ""
          - title: Install mysql
            url: ""
          - title: Install exec
            url: ""
      - title: Install from source