-- +migrate Up
CREATE INDEX `lnk_connections_flows` USING BTREE ON `connections`( `flow_id` );
CREATE INDEX `lnk_connections_flow_elements` USING BTREE ON `connections`( `element_from` );
CREATE INDEX `lnk_connections_flow_elements_2` USING BTREE ON `connections`( `element_to` );
CREATE INDEX `lnk_device_actions_devices` USING BTREE ON `device_actions`( `device_id` );
CREATE INDEX `lnk_scripts_device_actions` USING BTREE ON `device_actions`( `script_id` );
CREATE INDEX `index_address` USING BTREE ON `devices`( `address` );
CREATE INDEX `lnk_email_template_email_template` USING BTREE ON `email_templates`( `parent` );
CREATE INDEX `lnk_flows_flow_elements` USING BTREE ON `flow_elements`( `flow_link` );
CREATE INDEX `lnk_flow_elements_flows` USING BTREE ON `flow_elements`( `flow_id` );
CREATE INDEX `lnk_scripts_flow_elements` USING BTREE ON `flow_elements`( `script_id` );
CREATE INDEX `lnk_flows_workflows` USING BTREE ON `flows`( `workflow_id` );
CREATE INDEX `lnk_device_actions_map_device_actions` USING BTREE ON `map_device_actions`( `device_action_id` );
CREATE INDEX `lnk_images_map_device_actions` USING BTREE ON `map_device_actions`( `image_id` );
CREATE INDEX `lnk_map_devices_map_device_actions` USING BTREE ON `map_device_actions`( `map_device_id` );
CREATE INDEX `lnk_device_states_map_device_states` USING BTREE ON `map_device_states`( `device_state_id` );
CREATE INDEX `lnk_images_map_device_states` USING BTREE ON `map_device_states`( `image_id` );
CREATE INDEX `lnk_map_devices_map_device_states` USING BTREE ON `map_device_states`( `map_device_id` );
CREATE INDEX `lnk_images_map_devices` USING BTREE ON `map_devices`( `image_id` );
CREATE INDEX `lnk_maps_map_elements` USING BTREE ON `map_elements`( `map_id` );
CREATE INDEX `lnk_map_layers_map_elements` USING BTREE ON `map_elements`( `layer_id` );
CREATE INDEX `lnk_images_map_images` USING BTREE ON `map_images`( `image_id` );
CREATE INDEX `lnk_maps_map_layers` USING BTREE ON `map_layers`( `map_id` );
CREATE INDEX `lnk_roles_permissions` USING BTREE ON `permissions`( `role_name` );
CREATE INDEX `lnk_roles_roles` USING BTREE ON `roles`( `parent` );
CREATE INDEX `lnk_users_users_meta` USING BTREE ON `user_metas`( `user_id` );
CREATE INDEX `lnk_images_users` USING BTREE ON `users`( `image_id` );
CREATE INDEX `lnk_roles_users` USING BTREE ON `users`( `role_name` );
CREATE INDEX `lnk_users_users` USING BTREE ON `users`( `user_id` );
CREATE INDEX `lnk_workers_device_actions` USING BTREE ON `workers`( `device_action_id` );
CREATE INDEX `lnk_workers_flows` USING BTREE ON `workers`( `flow_id` );
CREATE INDEX `lnk_workers_workflows` USING BTREE ON `workers`( `workflow_id` );

-- +migrate Down
DROP INDEX `lnk_connections_flows` ON `connections`;
DROP INDEX `lnk_connections_flow_elements` ON `connections`;
DROP INDEX `lnk_connections_flow_elements_2` ON `connections`;
DROP INDEX `lnk_scripts_device_actions` ON `device_actions`;
DROP INDEX `lnk_device_actions_devices` ON `device_actions`;
DROP INDEX `index_address` ON `devices`;
DROP INDEX `lnk_email_template_email_template` ON `email_templates`;
DROP INDEX `lnk_flows_flow_elements` ON `flow_elements`;
DROP INDEX `lnk_flow_elements_flows` ON `flow_elements`;
DROP INDEX `lnk_scripts_flow_elements` ON `flow_elements`;
DROP INDEX `lnk_flows_workflows` ON `flows`;
DROP INDEX `lnk_device_actions_map_device_actions` ON `map_device_actions`;
DROP INDEX `lnk_images_map_device_actions` ON `map_device_actions`;
DROP INDEX `lnk_map_devices_map_device_actions` ON `map_device_actions`;
DROP INDEX `lnk_device_states_map_device_states` ON `map_device_states`;
DROP INDEX `lnk_images_map_device_states` ON `map_device_states`;
DROP INDEX `lnk_map_devices_map_device_states` ON `map_device_states`;
DROP INDEX `lnk_images_map_devices` ON `map_devices`;
DROP INDEX `lnk_maps_map_elements` ON `map_elements`;
DROP INDEX `lnk_map_layers_map_elements` ON `map_elements`;
DROP INDEX `lnk_images_map_images` ON `map_images`;
DROP INDEX `lnk_maps_map_layers` ON `map_layers`;
DROP INDEX `lnk_roles_permissions` ON `permissions`;
DROP INDEX `lnk_roles_roles` ON `roles`;
DROP INDEX `lnk_users_users_meta` ON `user_metas`;
DROP INDEX `lnk_images_users` ON `users`;
DROP INDEX `lnk_roles_users` ON `users`;
DROP INDEX `lnk_users_users` ON `users`;
DROP INDEX `lnk_workers_device_actions` ON `workers`;
DROP INDEX `lnk_workers_flows` ON `workers`;
DROP INDEX `lnk_workers_workflows` ON `workers`;

