export { default as AppMain } from './AppMain.vue'
export { default as NavbarDevelop } from './NavbarDevelop/index.vue'
export { default as NavbarDashboard } from './NavbarDashboard/index.vue'
export { default as Settings } from './Settings/index.vue'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as TagsView } from './TagsView/index.vue'
