// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AreaServiceClient is the client API for AreaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AreaServiceClient interface {
	// add new area
	AddArea(ctx context.Context, in *NewAreaRequest, opts ...grpc.CallOption) (*Area, error)
	// update area
	UpdateAreaByName(ctx context.Context, in *UpdateAreaRequest, opts ...grpc.CallOption) (*Area, error)
	// get area by id
	GetAreaByName(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*Area, error)
	// get area list
	GetAreaList(ctx context.Context, in *GetAreaListRequest, opts ...grpc.CallOption) (*GetAreaListResult, error)
	// delete area by id
	DeleteAreaByName(ctx context.Context, in *DeleteAreaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type areaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAreaServiceClient(cc grpc.ClientConnInterface) AreaServiceClient {
	return &areaServiceClient{cc}
}

func (c *areaServiceClient) AddArea(ctx context.Context, in *NewAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	out := new(Area)
	err := c.cc.Invoke(ctx, "/api.AreaService/AddArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaServiceClient) UpdateAreaByName(ctx context.Context, in *UpdateAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	out := new(Area)
	err := c.cc.Invoke(ctx, "/api.AreaService/UpdateAreaByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaServiceClient) GetAreaByName(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	out := new(Area)
	err := c.cc.Invoke(ctx, "/api.AreaService/GetAreaByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaServiceClient) GetAreaList(ctx context.Context, in *GetAreaListRequest, opts ...grpc.CallOption) (*GetAreaListResult, error) {
	out := new(GetAreaListResult)
	err := c.cc.Invoke(ctx, "/api.AreaService/GetAreaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaServiceClient) DeleteAreaByName(ctx context.Context, in *DeleteAreaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.AreaService/DeleteAreaByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AreaServiceServer is the server API for AreaService service.
// All implementations should embed UnimplementedAreaServiceServer
// for forward compatibility
type AreaServiceServer interface {
	// add new area
	AddArea(context.Context, *NewAreaRequest) (*Area, error)
	// update area
	UpdateAreaByName(context.Context, *UpdateAreaRequest) (*Area, error)
	// get area by id
	GetAreaByName(context.Context, *GetAreaRequest) (*Area, error)
	// get area list
	GetAreaList(context.Context, *GetAreaListRequest) (*GetAreaListResult, error)
	// delete area by id
	DeleteAreaByName(context.Context, *DeleteAreaRequest) (*emptypb.Empty, error)
}

// UnimplementedAreaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAreaServiceServer struct {
}

func (UnimplementedAreaServiceServer) AddArea(context.Context, *NewAreaRequest) (*Area, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArea not implemented")
}
func (UnimplementedAreaServiceServer) UpdateAreaByName(context.Context, *UpdateAreaRequest) (*Area, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAreaByName not implemented")
}
func (UnimplementedAreaServiceServer) GetAreaByName(context.Context, *GetAreaRequest) (*Area, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAreaByName not implemented")
}
func (UnimplementedAreaServiceServer) GetAreaList(context.Context, *GetAreaListRequest) (*GetAreaListResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAreaList not implemented")
}
func (UnimplementedAreaServiceServer) DeleteAreaByName(context.Context, *DeleteAreaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAreaByName not implemented")
}

// UnsafeAreaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AreaServiceServer will
// result in compilation errors.
type UnsafeAreaServiceServer interface {
	mustEmbedUnimplementedAreaServiceServer()
}

func RegisterAreaServiceServer(s grpc.ServiceRegistrar, srv AreaServiceServer) {
	s.RegisterService(&AreaService_ServiceDesc, srv)
}

func _AreaService_AddArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).AddArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AreaService/AddArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).AddArea(ctx, req.(*NewAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AreaService_UpdateAreaByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).UpdateAreaByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AreaService/UpdateAreaByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).UpdateAreaByName(ctx, req.(*UpdateAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AreaService_GetAreaByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).GetAreaByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AreaService/GetAreaByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).GetAreaByName(ctx, req.(*GetAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AreaService_GetAreaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).GetAreaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AreaService/GetAreaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).GetAreaList(ctx, req.(*GetAreaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AreaService_DeleteAreaByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AreaServiceServer).DeleteAreaByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AreaService/DeleteAreaByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AreaServiceServer).DeleteAreaByName(ctx, req.(*DeleteAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AreaService_ServiceDesc is the grpc.ServiceDesc for AreaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AreaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AreaService",
	HandlerType: (*AreaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddArea",
			Handler:    _AreaService_AddArea_Handler,
		},
		{
			MethodName: "UpdateAreaByName",
			Handler:    _AreaService_UpdateAreaByName_Handler,
		},
		{
			MethodName: "GetAreaByName",
			Handler:    _AreaService_GetAreaByName_Handler,
		},
		{
			MethodName: "GetAreaList",
			Handler:    _AreaService_GetAreaList_Handler,
		},
		{
			MethodName: "DeleteAreaByName",
			Handler:    _AreaService_DeleteAreaByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "area.proto",
}
