name: Build and Deploy

on:
  push:
    branches:
      - docs
    tags:
      - "*"

jobs:
  build:
    name: Build_Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up HUGO
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.89.4/hugo_extended_0.89.4_Linux-64bit.deb
          sudo dpkg -i hugo*.deb

      - name: Prepary deps
        run: |
          echo -e "machine github.com\n  login ${{ secrets.GUTHUBTOKEN }}" > ~/.netrc
          make get_deps

      - name: Build docs
        id: build-docs
        run: make docs_build

      - name: Deploy docs
        id: docs-deploy
        run: make docs_deploy
